### ISSUE TITLE
js dont Mnify

### ISSUE THREAD

**Issue by rodrigobarrocal** [tssajo/Minify#10]
In winxp uglifyjs only minify under shell if you run the cmd nodevars.bat before run uglify. with "pure" shell don´t minify

**Comment by tssajo** [comment]
@rodrigobarrocal Sorry for the late answer on this, but I just have an idea for you. If nodevars.bat needs to be invoked (in the opened new shell) before the uglify command can be used, then why don't you try this:
Please open the Default Settings of the Minify package:
Go to `Preferences -> Package Settings -> Minify -> Settings -- Default`
and copy the whole thing (all the settings) from this file and then open the User Settings of Minify package:
Go to `Preferences -> Package Settings -> Minify -> Settings -- User`
and paste all the default settings into this User Settings file.
Then still in this User Settings file find this line:
`// "uglifyjs_command": "/usr/local/bin/uglifyjs",`
and change it to this:
`"uglifyjs_command": "nodevars.bat & uglifyjs",`

Please let me know if it worked or not.

**Comment by tssajo** [comment]
This is regarding my suggested solution above.

The suggested `Minify` User setting:

`"uglifyjs_command": "nodevars.bat & uglifyjs",`

cannot be used in older than v1.1.4 versions of the `Minify` package. It just won't work.

However, with newer versions of the `Minify` plugin my suggested workaround should work!

I do not have the time to test it under Windows XP, but I am confident that my suggested solution can be used to fix the issue OP described, so I am closing this issue now. Just remember to use `Minify` v1.1.4+

If someone tests it on Windows XP and finds out that it did not solve the problem just notify me and I'll reopen this issue then.
