### ISSUE TITLE
Feature request: auto minify files on save

### ISSUE THREAD

**Issue by pascaliske** [tssajo/Minify#11]
Hi,

is it possible to add a setting for automatic minify a file on save?
This would make it easier because anytime you save a file it would minify the file and you don't have to do it manually after a few edits of the original file.

Thanks! :)

**Comment by tssajo** [comment]
In `Minify` v1.1.2 there is a new option (see `Minify.sublime-settings` file) called `auto_minify_on_save`. This implements the requested feature.
Note: It is advised to set `open_file` to `false` when you set `auto_minify_on_save` to `true`.
