### ISSUE TITLE
Beautify does not fire

### ISSUE THREAD

**Issue by Luckyfella73** [tssajo/Minify#12]
Hi Tssajo,
first thanks for your work! My problem is that I can't beatify a minified .css file while
minifying is working well using your package.
I'm working on OSX 10.9.4, Sublime Text 3.

I followed all of your instructions regarding OSX.

Do you have an idea what I could check to find out what to do to get the beautifying to work?
In most cases minifying is the task I need of course but once i a while beautifying can be quite
usefull.

Best regards
Luckyfella

**Comment by tssajo** [comment]
@Luckyfella73 Please read the updated [README.md](https://github.com/tssajo/Minify/blob/master/README.md) file
especially the section titled [IMPORTANT NOTE FOR MAC OS X USERS](https://github.com/tssajo/Minify/blob/master/README.md#important-note-for-mac-os-x-users)
Hopefully this will help you fix your problem. Let me know if not.

**Comment by tssajo** [comment]
I know this is an old thread, I just want to add the info that it is no longer required to change any PATH settings from Terminal on OS X ! `Minify` v1.1.5+ will just work out of the box. (Node.js and some Node.js CLI apps are still required of course, but all OS X PATH related  issues should be resolved for good.)

**Comment by Luckyfella73** [comment]
@tssajo I got it to work after following the instructions you provided - thanks for that! But nice to know the next install (if required one day) will be easier then :)
Have a nice week!
