### ISSUE TITLE
Minify stopped working, now only outputs an empty file

### ISSUE THREAD

**Issue by JMUkikster** [tssajo/Minify#13]
Hi,
I've been using your plugin for a while and LOVE it and then today it all of a sudden stopped working. No explanation for why. I didn't install anything new; the shortcut stopped working, the menu item stopped working as well.

I uninstalled it, reinstalled it, read through your install instructions again and can't for the life of me get it working! :( Sadly, this is very bad timing as I'm working to launch a site very soon and without minify working in Sublime Text 3 I'm really going to have some issues :(

Can you please help me?
I've got this in my /usr/local/bin folder

lrwxr-xr-x   1 root   wheel        54 Oct  2 10:22 css-beautify -> ../lib/node_modules/js-beautify/js/bin/css-beautify.js
lrwxr-xr-x   1 root   wheel        39 Jul 31 15:38 grunt -> ../lib/node_modules/grunt-cli/bin/grunt
lrwxr-xr-x   1 root   wheel        55 Oct  2 10:22 html-beautify -> ../lib/node_modules/js-beautify/js/bin/html-beautify.js
lrwxr-xr-x   1 root   wheel        53 Oct  2 10:22 js-beautify -> ../lib/node_modules/js-beautify/js/bin/js-beautify.js
-rwxr-xr-x   1 24561  wheel  20040480 Jun  9 11:22 node
lrwxr-xr-x   1 root   wheel        38 Jun 26 13:56 npm -> ../lib/node_modules/npm/bin/npm-cli.js
lrwxr-xr-x   1 root   wheel        33 Oct  2 10:23 svgo -> ../lib/node_modules/svgo/bin/svgo
lrwxr-xr-x   1 root   wheel        42 Oct  2 10:23 uglifyjs -> ../lib/node_modules/uglify-js/bin/uglifyjs

My console reads 
PLUGIN_DIR: /Users/kholl/Library/Application Support/Sublime Text 3/Packages/Minify
RUN_CMD_IN_SHELL: False
HAS_ASYNC_TIMEOUT: True
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2014-10-02 10:05:35, next run at 2014-10-02 11:05:35 or after
Minifying file /Users/kholl/Documents/SERVERS/Localhost-CIRESDEV/cires/css/style.css
Output file /Users/kholl/Documents/SERVERS/Localhost-CIRESDEV/cires/css/style.min.css
cmdToRun: ['java', '-jar', '/Users/kholl/Library/Application Support/Sublime Text 3/Packages/Minify/bin/yuicompressor-2.4.7.jar', '/Users/kholl/Documents/SERVERS/Localhost-CIRESDEV/cires/css/style.css', '-o', '/Users/kholl/Documents/SERVERS/Localhost-CIRESDEV/cires/css/style.min.css', '--charset', 'utf-8', '--line-break', '250']
Reloading /Users/kholl/Documents/SERVERS/Localhost-CIRESDEV/cires/css/style.min.css

but the style.min.css file is completely empty.

Do you have any suggestions on what I can try? 

My user settings for Minify.sublime-settings have this line, as I saw suggested in some other posts...
    "uglifyjs_command": "/usr/local/bin/uglifyjs",

Would appreciate any help you can provide ASAP.

Thanks!
-Kiki

**Comment by tssajo** [comment]
FYI:

Beginning v1.1.3 :

Error output is show in an alert box. E.g: when attempting to minify a JavaScript file containing syntax errors.
