### ISSUE TITLE
Java dependency

### ISSUE THREAD

**Issue by codemakerlive** [tssajo/Minify#15]
It seems to be a little heavy to require Java installation just to use the YUI Compressor, given the amount of css minifiers available and that the other tools use node.js. 

Would it be possible to switch to a node package such as clean-css, or perhaps cancel out specific tool conversions in the plug-ins settings? 

Thanks.

**Comment by mkormendy** [comment]
This sublime package relies on a lot of node packages, why not just use the node yui compressor? https://www.npmjs.com/package/yuicompressor

**Comment by tssajo** [comment]
"/It still uses Java under the hood/"

However, switching to Clean-CSS ( 
https://github.com/jakubpawlowicz/clean-css ) is planned for quiet some 
time.
I start working on its addition to the Minify package today.

**Comment by mkormendy** [comment]
Ha! I deleted that post shortly after I posted it after reading more about the inner workings of the node yuicompressor.
Can't wait to see the Clean-CSS implementation.

**Comment by tssajo** [comment]
Or actually we can use UglifyCSS ( https://github.com/fmarcia/UglifyCSS ) which is a true javascript port of YUI compressor (for CSS minification). I should probably make Minify package to be user configurable on which library to use for CSS minification.

**Comment by mkormendy** [comment]
That's actually a nicer option,.. I like the counterpart nomenclature "beautify" and "uglify" ;-)

**Comment by tssajo** [comment]
In `Minify` version 1.1.0 [clean-css](https://www.npmjs.com/package/clean-css) is the default CSS minifier. Java is no longer a dependency!

Notes:

[uglifycss](https://www.npmjs.com/package/uglifycss) is also supported;

although not recommended, the Java based `YUI compressor` can still be used, here is how (extract from [Minify.sublime-settings](https://github.com/tssajo/Minify/blob/master/Minify.sublime-settings)) :

	// ############################
	// #  CSS Processing Options  #
	// ############################

	// you can specify which CSS minifier to use such as "clean-css", "uglifycss" or "yui"
	// notes: the default is "clean-css"; you must have java installed for "yui"
	// "cssminifier": "clean-css",
