### ISSUE TITLE
Some particluar js files are not getting minified properly

### ISSUE THREAD

**Issue by rahuljadav** [tssajo/Minify#17]
I am having top-login.js and main.js file and running sublime3 on windows 8.1

When i try to minify using ctrl+alt+m on this file the below output comes in console.
and the .min.js files doesn't open.

It works fine with other js file

Minifying file E:\htdocs\appvigil-saas-website\js\top-login.js
Output file E:\htdocs\appvigil-saas-website\js\top-login.min.js
cmdToRun: ['uglifyjs', 'E:\\htdocs\\appvigil-saas-website\\js\\top-login.js', '-c', '-m', '-o', 'E:\\htdocs\\appvigil-saas-website\\js\\top-login.min.js']

**Comment by tssajo** [comment]
This sort of issue happened to me once when the js file I was trying to minify had some syntax errors. (Count of opening and closing curly brackets did not match.)

Try to open a Cmd prompt and run the following command manually:

`uglifyjs E:\htdocs\appvigil-saas-website\js\top-login.js -c -m -o E:\htdocs\appvigil-saas-website\js\top-login.min.js`

What do you get?

**Comment by rahuljadav** [comment]
Hi Zoltan,

Thanks for the quick reply.
My files had some brackets and semicolon missing which i founded manually.
After that the minify process was working properly.

It would be great if the error displaying popup or message can be shown in sublime console or  just open an error text file in next tab stating that due to the error in the files the minify process couldn't  be completed.

It will be an great addon to the plugin.

Thanks,

**Comment by tssajo** [comment]
I understand that it would be great, but I do not have time right now to implement such feature. (I would need to capture the error output and display it. I might eventually do this, but I can't promise anything.)

In a related note: I recommend you to install [SublimeLinter](http://www.sublimelinter.com/en/latest/) alone with `SublimeLinter-jshint` package and this would show your syntax errors inside JavaScript code blocks within the Sublime Text editor. `SublimeLinter` is a great real-time syntax checking tool, which I use all the time (and not just for JavaScript). It's a highly recommended tool!

**Comment by tssajo** [comment]
@rahuljadav The requested feature "error displaying popup" has been added to `Minify` version 1.1.3
You can test it with a broken JavaScript file (just attempt to minify one) and see if the parse error message is showing up for you inside Sublime Text.
Please let me know if you encounter any issues. Thanks!
