### ISSUE TITLE
Minify plugin is disabled in the css file after the last update

### ISSUE THREAD

**Issue by Nanod10** [tssajo/Minify#18]
I can not minify CSS files even js files.
After the last update, the context menu Minify has disabled items.
The key combination Ctrl + Alt + M do not work.
I am a Windows user, as you indicate installing NPM modules required and then update them.
Reinstalling the plugin with even Sublime Text 3 restart does not work.

What I can do?

**Comment by tssajo** [comment]
Thanks for reporting the issue. After doing some tests I believe I was able to fix it. I just released `Minify` v1.1.1 please update and let me know if it resolved the issue for you or not. Thanks!

Please note that it may take a while until Package Control notices the new v1.1.1 version. You can check that here: https://packagecontrol.io/packages/Minify
