### ISSUE TITLE
Minify.sublime-settings has last comma before close bracket

### ISSUE THREAD

**Issue by handycomm** [tssajo/Minify#19]
I encountered error. Because changed Minify.sublime-settings.
Minify.sublime-settings. 75 line.
```
{
     //...
     "html-minifier_options": "--remove-comments --remove-comments-from-cdata --collapse-whitespace --conservative-collapse --collapse-boolean-attributes --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes --minify-js --minify-css",
}
```

I remove comma from minify-js --minify-css", and it worked.

**Comment by tssajo** [comment]
Thanks for reporting this. I will fix this in the next release of `Minify`. Expect it later today.

**Comment by tssajo** [comment]
`Minify` v1.1.2 has been released. It fixes the reported problem in the `Minify.sublime-settings` file.
