### ISSUE TITLE
Source maps

### ISSUE THREAD

**Issue by mike-anthony** [tssajo/Minify#20]
I think that source maps should be supported.

```py
if sublime.load_settings('Minify.sublime-settings').get('source_map'):
    cmdToRun.extend(['--source-map', outfile + '.map'])
```

I'm sure this implementation is a little too basic, and could be improved, but this is nice for now.

:beers:

**Comment by mike-anthony** [comment]
Though, I see the issue there - it uses the full path. Any way to not specify the URL in the original file? I believe jQuery works like that, where the assumption is that the map file name is amended with `.map`, and that the browser will find it...

**Comment by mike-anthony** [comment]
Perhaps this is better?

```py
if sublime.load_settings('Minify.sublime-settings').get('source_map'):
	head, tail = ntpath.split(outfile)
	mapfile = tail or ntpath.basename(head)
	cmdToRun.extend(['--source-map', outfile + '.map', '--source-map-url', mapfile + '.map'])
```

**Comment by tssajo** [comment]
Personally, I never used .map files in my life... But I know what those are good for.

If you can get it working then feel free to submit a PR and I will merge.

Thanks!

**Comment by mike-anthony** [comment]
I'll give it another bash tomorrow and submit a PR - there must be something really simple that I'm missing...

**Comment by tssajo** [comment]
Maybe we would need to `cd` into that directory where the original file is and issue the `uglify` command  from there with just the input file's name (with no path) ? Do you think that would help?

**Comment by mike-anthony** [comment]
That certainly sounds logical. It's just weird that Uglify doesn't use format used in `--source-map-url` in the map itself... The alternative would be to generate the map using the above method, then open the file and strip the path, leaving the file name behind.

**Comment by mike-anthony** [comment]
I have found the solution. For the most part, people want a simple way to make source maps beside their minified and original counterparts. This does the trick:

```py
if sublime.load_settings('Minify.sublime-settings').get('source_map'):
    head, tail = ntpath.split(outfile)
    mapfile = tail or ntpath.basename(head)
    cmdToRun.extend(['--source-map', outfile + '.map', '--source-map-url', mapfile + '.map', '--source-map-root', './', '-p', 'relative'])
```

Which generates something similar to this:

```json
{
  "version": 3,
  "file": "site.min.js",
  "sources": [
    "site.js"
  ],
  "names": ["REDACTED FOR BREVITY"],
  "mappings": "REDACTED FOR BREVITY",
  "sourceRoot": ".\/"
}
```

**Comment by tssajo** [comment]
Thanks!
I'll implement source-map option for CSS minify too ( https://github.com/jakubpawlowicz/clean-css#using-cli ) then I'll release a new version.

**Comment by mike-anthony** [comment]
Great :+1: 

Just submitted another PR as I forgot to add `ntpath` to the list of imports.

**Comment by tssajo** [comment]
Thanks! I noticed the missing `ntpath` import too. Don't worry. :+1:

**Comment by mike-anthony** [comment]
:+1: :beers:
