### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by smlombardi** [tssajo/Minify#25]
I installed the package and the node tools, verified node tools worked in terminal.

Restarted Sublime (3083).  Open HTML file and run Minimize command.  Nothing happens and the Sublime terminal reads:
````
Minify: Minifying file /Users/stevel/Documents/Freelance/Elmridge/Email blasts/Email blast 41 - OTC/otc.html
Traceback (most recent call last):
  File "/Users/stevel/Library/Application Support/Sublime Text 3/Packages/Minify/Minify.py", line 77, in <lambda>
    sublime.set_timeout_async(lambda: self.do_action(), 0)
  File "/Users/stevel/Library/Application Support/Sublime Text 3/Packages/Minify/Minify.py", line 187, in do_action
    self.minify(self.view)
  File "/Users/stevel/Library/Application Support/Sublime Text 3/Packages/Minify/Minify.py", line 145, in minify
    self.run_cmd(cmdToRun, outfile)
  File "/Users/stevel/Library/Application Support/Sublime Text 3/Packages/Minify/Minify.py", line 63, in run_cmd
    retCode, output = self.runProgram(cmdToRun)
  File "/Users/stevel/Library/Application Support/Sublime Text 3/Packages/Minify/Minify.py", line 26, in runProgram
    p = subprocess.Popen(cmdToRun, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=RUN_IN_SHELL)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'html-minifier'
````

**Comment by tssajo** [comment]
You don't say what platform are you on. But I assume you are on Mac OS X. If that is right, read the installation instructions in the README file, especially this section:

https://github.com/tssajo/Minify#important-note-for-mac-os-x-users

If you're not on Mac OS X, let me know and I'll re-open this issue for you.

**Comment by smlombardi** [comment]
I am on OSX 10.10.3.  And I did follow that note.  I still get
````
Minify: Minifying file /Users/stevel/Documents/Freelance/Elmridge/Email blasts/Email blast 41 - OTC/otc.html
Traceback (most recent call last):
  File "/Users/stevel/Library/Application Support/Sublime Text 3/Packages/Minify/Minify.py", line 77, in <lambda>
    sublime.set_timeout_async(lambda: self.do_action(), 0)
  File "/Users/stevel/Library/Application Support/Sublime Text 3/Packages/Minify/Minify.py", line 187, in do_action
    self.minify(self.view)
  File "/Users/stevel/Library/Application Support/Sublime Text 3/Packages/Minify/Minify.py", line 145, in minify
    self.run_cmd(cmdToRun, outfile)
  File "/Users/stevel/Library/Application Support/Sublime Text 3/Packages/Minify/Minify.py", line 63, in run_cmd
    retCode, output = self.runProgram(cmdToRun)
  File "/Users/stevel/Library/Application Support/Sublime Text 3/Packages/Minify/Minify.py", line 26, in runProgram
    p = subprocess.Popen(cmdToRun, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=RUN_IN_SHELL)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'html-minifier'
````

**Comment by tssajo** [comment]
I'm sorry to hear that. Please open up a Terminal and issue the following commands and tell me what you get from each:

`whoami`

`node --version`

`which node`

`html-minifier --version`

`which html-minifier`

`cat /etc/launchd.conf`

`cat /etc/paths`

`echo $PATH`

This will help to diagnose the issue. Get back to me with the results and I'll help you solve the problem.

**Comment by smlombardi** [comment]
whoami

    stevel

node --version

    v0.12.2

which node

    /usr/local/bin/node

html-minifier --version

    html-minifier v0.7.2

which html-minifier

    /usr/local/bin/html-minifier

cat /etc/launchd.conf

    setenv PATH /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

cat /etc/paths

    /usr/local/bin

    /usr/bin

    /bin

    /usr/sbin

    /sbin

echo $PATH


  /usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by tssajo** [comment]
Thanks for the info! Everything you sent looks perfectly good. I can only ask one last question: After you have added "setenv PATH /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin" to your `/etc/launchd.conf` file, have you rebooted your computer? That needs to be done before that change takes effect. If not, please reboot it and try again. If it still does not work after that then please let me know!

You see, quiet a few people are having this exact same issue but only on Mac OS X. I want to be able to help them. I do not own a Mac myself, but I can run OS X in a virtual machine. I currently have OS X 10.9 installed as a VM and last night I was able to reproduce the issue you are having. But I was able to solve that by adding "setenv PATH /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin" to the `/etc/launchd.conf` file and after rebooting everythng started to work. If it does not work for you then I don't know what to say, but I would really get to the bottom of this. I might need to install a fresh OS X 10.10 in a new VM to test this out. So please let me know if rebooting helped you or not. Thanks!

**Comment by smlombardi** [comment]
yes, i rebooted before i tried to run the plugin.

**Comment by tssajo** [comment]
Yeah, I believe you. After a lot more research I found this: http://apple.stackexchange.com/questions/106355/setting-the-system-wide-path-environment-variable-in-mavericks
basically it says that the `/etc/launchd.conf` method no longer works for setting a system wide PATH in OS X 10.10 :(
I investigate further and I'll get back to you.
Thanks for reporting this issue to me!

**Comment by tssajo** [comment]
Okay, so according to that post, you need to create a new file: `~/Library/LaunchAgents/my.startup.plist`

with the following contents:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>my.startup</string>
  <key>ProgramArguments</key>
  <array>
    <string>sh</string>
    <string>-c</string>
    <string>launchctl setenv PATH /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
```

After this I would say please reboot again.

An important note: This will fix the PATH issues of applications which you launch after the reboot. This method doesn't apply to applications that are reopened at login if "Reopen windows when logging back in" is checked!!

Please try this and let me know if it helped you or not. Thanks!!

**Comment by tssajo** [comment]
I'll probably have a better solution soon!

**Comment by smlombardi** [comment]
FWIW all other node-powered packages work fine.

**Comment by tssajo** [comment]
I know. I already have a new working version of `Minify` here on my local PC which runs fine in OS X 10.9 without needing to configure any PATH environments in Terminal whatsoever. I'll release the new version very soon. But I test it first in OS X 10.10
If testing goes well, I'll probably be able to release the new version in a few hours.

**Comment by tssajo** [comment]
@smlombardi I just released new v1.1.5 version of `Minify`. This one fixes all PATH related issues on OS X. I personally tested it on OS X 10.8, OS X 10.9 and OS X 10.10 so I am quiet certain it will work for you, too.

BTW, there is no need to change any PATH related settings from `Terminal` anymore! (However, if you already added some paths, its okay, it won't hurt so no need to revert any of those changes.)

**Comment by smlombardi** [comment]
I confirm it works here as well.  Many thanks.

**Comment by tssajo** [comment]
Great to hear that! Thanks for reporting the issue and not giving up on my plugin! :)
