### ISSUE TITLE
Feature request: Support for JSON files

### ISSUE THREAD

**Issue by victorleblais** [tssajo/Minify#26]
Hello,
Since Minify already supports JS files, it would be great to **support .json files**.
It's "already" implemented: renaming a `.json` file in `.js` and adding `var data =` at the beginning turns the JSON into a valid JS file, but yeah, it's not practical at all.

Thanks !

**Comment by tssajo** [comment]
JSON minification / beautification has been added to version 1.2.0 of `Minify`.

Do not forget to issue the following commands in your shell / Terminal :

`npm install -g clean-css uglifycss js-beautify html-minifier uglify-js minjson svgo`

followed by:

`npm update -g clean-css uglifycss js-beautify html-minifier uglify-js minjson svgo`
