### ISSUE TITLE
Save minifyed file to a relative path instead in the same folder

### ISSUE THREAD

**Issue by hennott** [tssajo/Minify#29]
In my Case all development sources are stored in a subfolder "_dev" and during minify I need to save the files to the upper main directory. Is it possible to set a relative path?

**Comment by tssajo** [comment]
No, it is currently not possible to set any custom path to store the minified (or beautified) files into. We don't mangle the paths, we save the changed (minified or beautified) files in the same directory where the original files are. For simplicity.
