### ISSUE TITLE
Feature Request - Disable the minification of .min files!

### ISSUE THREAD

**Issue by kayrusdotcom** [tssajo/Minify#30]
Hi!
I've really enjoyed your Minify package, but one issue I've consistently encountered is with saving minified files. Since I use an FTP package which auto-uploads on save alongside Minify's auto-minify on save setting, I often have to save a minified file, which creates a frustrating filename.min.min.etc file. I would greatly appreciate it if there were a setting to disable the minification of already minified files.
Thank you.

**Comment by tssajo** [comment]
Hi,
Yeah, I also purchased the SFTP plugin from wbond which does auto-upload on save. I don't use that plugin these days anymore. But I know what you're talking about. Okay, I'll add the exclusion of minifying files which already have a .min file extension. I don't know when this will be ready, but it will be done sooner or later.
Thanks for the feature suggestion!

**Comment by tssajo** [comment]
@kayrusdotcom The requested feature is implemented in version 1.2.1 . Please update to 1.2.1 when it shows up in [Package Control](https://packagecontrol.io/packages/Minify). You do not need to change any configuration setting, `Minify`'s `auto_minify_on_save` function will automatically skip minifying the file if the file has .min in its file name. Note: You can still minify any file by invoking `Minify`from the menu or from keyboard shortcut. This change only affects the `auto_minify_on_save` function.
