### ISSUE TITLE
ST3 on Yosemite 10.10.4 , Minification of CSS fails

### ISSUE THREAD

**Issue by Luckyfella73** [tssajo/Minify#35]
Hi tssajo,
I installed your ST3 plugin and when minifying js sublim saves the .min version successfully. But when I try to minify css nothing happens. I tryed to solve the problem by studying the other thread where js minifying didn't work but without success. In case you have the time to help me, here are the infos you asked for in the other thread:

whoami
```
imsungu
```

node --version
```
v0.10.22
```

which node
```
/usr/local/bin/node
```

html-minifier --version
```
html-minifier v0.7.2Karstens-MBP-2:bin imsungu$
```

which html-minifier
```
/Users/imsungu/.npm-packages/bin/html-minifier
```

cat /etc/launchd.conf
```
cat: /etc/launchd.conf: No such file or directory
```

cat /etc/paths
```
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

echo $PATH
```
/Users/imsungu/.npm-packages/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/Applications/MAMP/bin/php/php5.5.14/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin
```

*cat /etc/launchd.conf* gives me an error message but I don't know how to solve that one.

Would be very nice if I could get your plugin to work with minifying CSS.

Best regards,
Luckfella

**Comment by tssajo** [comment]
@Luckyfella73
Hi,
Please open up a Terminal and issue the following command:

`npm install -g clean-css uglifycss js-beautify html-minifier uglify-js minjson svgo`

Once done, issue the following command too (still in Terminal) :+1: 

`npm update -g clean-css uglifycss js-beautify html-minifier uglify-js minjson svgo`

You can exit from your Terminal now and go back to ST3 editor. Try to minify your CSS file. If it still does not work then please let me know and I'll give you further instructions on how to proceed.

If it helped then please also let me know so I can close this ticket. Thanks!

**Comment by Luckyfella73** [comment]
I fired the two commands on my terminal but it's still not working. when doing the npm install command I noticed 1 error message on the download-log lines - here the first 7 lines where the error was:

npm http GET https://registry.npmjs.org/clean-css
npm http GET https://registry.npmjs.org/uglifycss
npm http GET https://registry.npmjs.org/html-minifier
npm http GET https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/minjson
npm http GET https://registry.npmjs.org/svgo
npm ERR! not a package /var/folders/w_/2zfvqf196h9fkkdvzx7njgpm0000gn/T/npm-5090-VNBQbLR9/1439309244091-0.9116691262461245/tmp.tgz

**Comment by tssajo** [comment]
In that case your Node.js installation is broken. You should reinstall Node.js ! How did you install it in the first place? Did you just downloaded it from Nodejs.org ? In that case, I recommend you to download the latest version from the v0.10.x. series here:
http://nodejs.org/dist/v0.10.40/node-v0.10.40.pkg
and install it (on top of your existing installation).
But if you installed node.js from e.g. [Homebrew](http://brew.sh/) then please reinstall Node.js via Homebrew!
Either way, you must fix your broken Node.js installation first, because `Minify` for SublimeText depends on Node.js CLI programs.
Let me know how the reinstallation of Node.js goes.

**Comment by tssajo** [comment]
In addition to the above, you should also issue the following command from Terminal:

`npm cache clean`

followed by:

`npm update -g`

and after this, try to issue the two other npm commands from above.
I still recommend you to upgrade from Node.js v0.10.22 to v0.10.40 as the latter has some security fixes, etc. It's still from the v0.10.x series, so everything should still work like before, there should be no compatibility problems.

**Comment by tssajo** [comment]
Also, when you run the following command from Terminal, what do you get?

`npm list -g --depth=0`

**Comment by Luckyfella73** [comment]
running:
$ npm list -g --depth=0

I get:

/Users/imsungu/.npm-packages/lib
├── bower@1.4.1
├── browser-sync@2.7.12
├── clean-css@3.3.9
├── dploy@1.2.0
├── generator-bbb@0.3.4
├── grunt-cli@0.1.13
├── html-minifier@0.7.2
├── js-beautify@1.5.10
├── minjson@0.0.1
├── shipit-cli@1.3.0
├── svgo@0.5.5
├── uglify-js@2.4.24
├── uglifycss@0.0.17
└── yo@1.1.2

npm ERR! max depth reached: bower@1.4.1, required by undefined@undefined
npm ERR! max depth reached: browser-sync@2.7.12, required by undefined@undefined
npm ERR! max depth reached: clean-css@3.3.9, required by undefined@undefined
npm ERR! max depth reached: dploy@1.2.0, required by undefined@undefined
npm ERR! max depth reached: generator-bbb@0.3.4, required by undefined@undefined
npm ERR! max depth reached: grunt-cli@0.1.13, required by undefined@undefined
npm ERR! max depth reached: html-minifier@0.7.2, required by undefined@undefined
npm ERR! max depth reached: js-beautify@1.5.10, required by undefined@undefined
npm ERR! max depth reached: minjson@0.0.1, required by undefined@undefined
npm ERR! max depth reached: shipit-cli@1.3.0, required by undefined@undefined
npm ERR! max depth reached: svgo@0.5.5, required by undefined@undefined
npm ERR! max depth reached: uglify-js@2.4.24, required by undefined@undefined
npm ERR! max depth reached: uglifycss@0.0.17, required by undefined@undefined
npm ERR! max depth reached: yo@1.1.2, required by undefined@undefined

I'm not 100% sure if I installed node via homebrew, it was a while ago I did that.. I'm trying to find out just now and then I'm going to follow your instructions above.

**Comment by tssajo** [comment]
To find out if you have Homebrew installed, run this:

`brew list`

It lists the packages installed via Homebrew. If you see Node.js on that list, then you installed Node.js via Homebrew. Let me know.

**Comment by tssajo** [comment]
If you do have Homebrew installed then you can try to do this too:

`brew update`

followed by

`brew doctor`

Obviously only run these if you happen to have Homebrew installed on your system.

**Comment by tssajo** [comment]
Also, send me the output of the following commands:

`which cleancss`

and

`cleancss --version`

**Comment by Luckyfella73** [comment]
which cleancss returns:
```
/Users/imsungu/.npm-packages/bin/cleancss
```

cleancss --version returns:
```
3.3.9
```

npm update -g did print out a lot of error messages or warnings like "outdated xcode" and so on. I try to fix that first.

**Comment by tssajo** [comment]
Yeah, you need to go to App Store (I think) and download the latest XCode.
http://stackoverflow.com/questions/15417619/how-do-you-update-xcode-on-osx-to-the-latest-version

**Comment by Luckyfella73** [comment]
@tssajo It took a while to update xCode and in between my node installation didn't work due to broken symlinks, but now I got it all to run again except css minifying. Maybe it's because I now installed the newest node version? I missed your advice to install a version in between v0.10.22 to v0.10.40.

If you still have an idea what I could try it would be nice. On the other hand I don't want to bother you too long..

**Comment by tssajo** [comment]
So now you have Node.js v0.10.40 installed? Also when you run `npm update -g` you no longer get any errors?

What is the output of the following now?

`which node`

`node --version`

`which cleancss`

`cleancss --version`

Anyway, I think now the problem is in your `Minify`'s settings file:
*(Preferences > Package Settings > Minify > Settings - User)*
When you open this settings file, do you see an entry there for `"cleancss_command"`? What is the value?

**Comment by Luckyfella73** [comment]
`npm update -g` returns no errors anymore

which node
`/usr/local/bin/node`

node --version
`v0.12.7`

which cleancss
`/Users/imsungu/.npm-packages/bin/cleancss`

cleancss --version
`3.3.9`

Opening the package-settings file I found that the line containing `cleancss_command ` is commented out.

...

After writing the answer to your last question I removed the comment chars and pasted the path that was returned by `which cleancss`. After closing and reopening Sublime CSS minifying works now!!

Thanks a lot tssajo for taking the time to help me getting that to work! I appreciate that very much!

Best regards
Luckyfella

**Comment by tssajo** [comment]
@Luckyfella73 I'm glad that it finally works! I think you may want to check the other `*_commands` in that settings file and may want to set the proper absolute path to the other utilities as well such as `js-beautify_command`, `uglifyjs_command`, `html-minifier_command`, etc. I guess that your `uglifyjs_command` is already set, otherwise Javascript minification would not work... Also make sure that you edit the `Settings - User` file and NOT the `Settings - Default` file!! Otherwise your changes will be overwritten on the next release of `Minify`.
