### ISSUE TITLE
Minify/Beautify to a dirty view instead of a file

### ISSUE THREAD

**Issue by qkdreyer** [tssajo/Minify#38]
That would be great to have a settng that would allow user to minify / beautify his current view to a new dirty view (unsaved) instead of outputing to a saved file (.min / .beautified)

**Comment by tssajo** [comment]
While this might sound like a cool new feature idea, here is the reason why I hesitant to implement it:

From my Sublime Text plugin program code (which is written in Python) I call outside (aka 3rd party) programs which are written in Javascript and those Javascript (Node.js) programs are doing the actual minification / beautification task. These 3rd party programs are placing the results into a file, so I can only give these programs an output file name (e.g. results.min.js) and the results are put into this file.

So now, when you know how it all works under the hood, isn't it simpler to just open that resulting file in a Sublime view rather then getting out the data from that already existing file into a "new dirty view" and then deleting that file? I hope you understand my point.
