### ISSUE TITLE
Mac HTML Minify

### ISSUE THREAD

**Issue by jamiegiftbit** [tssajo/Minify#39]
I'm getting the following error trying to minify and can't find any info on fixing it.

```
html-minifier --remove-comments --remove-comments-from-cdata --collapse-whitespace --conservative-collapse --collapse-boolean-attributes --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes --minify-js --minify-css -o /project-path/litmus-verison.min.html /project-path/litmus-verison.html

[31mERROR[0m: Unknown option --remove-comments-from-cdata

```

**Comment by tssajo** [comment]
@jamiegiftbit Thanks for letting me know about this problem! Here is what's going on:
My `Minify` plugin uses the following 3rd party program to minify HTML files: [html-minifier](https://github.com/kangax/html-minifier) and the long-existing option `removeCommentsFromCDATA` got removed from the `html-minifier` program less than a week ago, see: [eliminate removeCommentsFromCDATA](https://github.com/kangax/html-minifier/commit/97c9bfb143de98ca44c3acbed15aac4a9ebec0ef)
This is the reason why your got the error message:
`Unknown option --remove-comments-from-cdata`

I'll release an updated version of my `Minify` plugin, but until then here is a workaround: In Sublime Text go to Preferences -> Package Settings -> Minify -> Settings -- Default and locate the following line:
```
	"html-minifier_options": "--remove-comments --remove-comments-from-cdata --collapse-whitespace --conservative-collapse --collapse-boolean-attributes --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes --minify-js --minify-css",
```
and change it to:
```
	"html-minifier_options": "--remove-comments --collapse-whitespace --conservative-collapse --collapse-boolean-attributes --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes --minify-js --minify-css",
```

Please let me know if this helped.

**Comment by tssajo** [comment]
`Minify` version 1.2.3 fixes the problem.
