### ISSUE TITLE
'let' is not supported?

### ISSUE THREAD

**Issue by House3272** [tssajo/Minify#43]
`for (let i = 0;...` did not work, but ran successfully when I changed it to `for (var i = 0;...`

**Comment by tssajo** [comment]
@House3272
The `Minify` ST plugin uses an external program for javascript minification: [UglifyJS2](https://github.com/mishoo/UglifyJS2)

I suggest you to update your UglifyJS2 program to the latest version:
`npm update -g uglify-js`
and see if that helps.

If it did not help then please report this issue to the maintainers of UglifyJS2 here: https://github.com/mishoo/UglifyJS2/issues

Thanks!

**Comment by House3272** [comment]
Ah thanks.
It seems like that project doesn't support ES6 yet.
