### ISSUE TITLE
comments_to_keep with "complex" regexp

### ISSUE THREAD

**Issue by Gates33** [tssajo/Minify#44]
I try to use it in order to have 2+ match word with my comments

so I used '|' => "/foo|bar/" 
and group '()'=> "/(foo|bar)/"  or "/(foo)?(bar)?/" 

and i get error like : 

`File "D:\Sublime Text 3\Data\Packages\Minify\Minify.py", line 70, in run_cmd
    self.handle_result(cmd, outfile, retCode, output)
  File "D:\Sublime Text 3\Data\Packages\Minify\Minify.py", line 53, in handle_result
    sublime.error_message(' '.join(cmd) + '\r\n\r\n' + output.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 83: invalid start`

**Comment by tssajo** [comment]
@Gates33 Sorry for the late reply... :(
Please try to escape the | character, like this:
```
    "comments_to_keep": "/foo\|bar/",
```
or:
```
    "comments_to_keep": "/\(foo\|bar\)/",
```
This sort of escaping should work on Linux and OSX, probably won't work on Windows, though... :(

Hopefully this will do the trick for you. If not, then unfotunately I do not know how to fix this... :(

**Comment by tssajo** [comment]
One more idea:

If the above still do not work then you can try to double escape, like this:
```
    "comments_to_keep": "/foo\\|bar/",
```
or:
```
    "comments_to_keep": "/\\(foo\\|bar\\)/",
```

**Comment by Gates33** [comment]
Hi tssajo

I'm on windows.

I got an error when I save the setting file with the simple escape.

anyway, neither simple escape, nor double escape works :(

The goal was to keep the "userscript option" for greasemonkey/tampermokey

https://wiki.greasespot.net/Metadata_Block

// ==UserScript==
// @key value
// @key2 value2
// ==/UserScript=
console.log("your code after");

**Comment by tssajo** [comment]
@Gates33 If you are on Windows then please try it like this:

```
    "comments_to_keep": "\"/(foo|bar)/\"",
```

Please let me know if it worked or not. Thanks!

**Comment by Gates33** [comment]
I got no error this time,
but all the comments are deleted
I also trie with a simple : 
`"comments_to_keep": "\"/foo/\"",`

**Comment by tssajo** [comment]
So this simple way did not work either:
```
"comments_to_keep": "\"/foo/\"",
```
?

**Comment by Gates33** [comment]
that's right, the "simple" way did not work neither

to be clear, it minified all the JS without any comment

**Comment by Gates33** [comment]
close by mistake

**Comment by tssajo** [comment]
@Gates33 I spent quiet some time on this, but I managed to find the solution!

On Windows (and only on Windows!) you need to escape special characters with three ^ characters.

Examples of some special characters are: <, >, (, ), |

Here is the correct way of escaping the pipe character in your settings file:
```
	"keep_comments": true,
	"comments_to_keep": "/foo^^^|bar/",
```
I tested the above on my Windows 7 PC and it works as expected.

If you must use brackets, then escape those, too. Like this:
```
	"keep_comments": true,
	"comments_to_keep": "/^^^(foo^^^|bar^^^)/",
```
I also tested this one on Windows and it worked as expected, too.

I hope this finally resolves your issue.

**Comment by Gates33** [comment]
Hi @tssajo,

Indeed it works with the tripple ^

So for greasemonkey metadablock, i can use

`"comments_to_keep": "/^^^(@^^^|UserScript^^^)/",`

Thx ! 

best regards
