### ISSUE TITLE
Would it be possible to add option to Beautify?

### ISSUE THREAD

**Issue by superlativo77** [tssajo/Minify#46]
First congratulations on the Minify + Beautify package. I know that this section is for errors and I just want to offer a proposal. Sorry if it is not the way but I did not find a way to offer an idea. 

I am a novice developer and would like to propose if it is possible to add an option to configure Beautify. The idea is to be able to configure it to be saved in the same file and not create a new one. Or just perform the task and the user will save it later.

I understand the file extension for the minified versions but in my case I use Beautify because I want my file well indented and I do not want a new one.

It's just an idea. Thank you.

**Comment by tssajo** [comment]
@superlativo77 Well, thanks for the idea. I might implement it some day, however this is not trivial to implement. Here is the reason why: the `Minify` ST plugin is using external dependencies to do the actual job of both minifying and beautifying. Those external commands are run from the command line. Currently those programs put the output (e.g. the beautified file) to a file on the disk. So currently we just tell those external programs a PATH to a file as the destination of their output.

To implement what you want, we would need to change the `Minify` plugin to work like this: We would still need to call the external program to do the actual job (e.g. minifying) but we should either capture the output and replace the current View in ST with the results, or we would need to tell the external program to save the output to a temporary file and once done, we'd need to read the data from the temporay file, delete the temporary file, and replace the current View in ST with that data.

Currently, we like to keep things simple (we love the KISS principle) hence we do not manipulate any View's of ST. We just call the external programs (tools) to create new files. That's it. This is why the Minify plugin is so small and fast. We do not want to complicate things. Your requested feature is a nice one, but it would require our program (the `Minify` plugin) to start manipulating View windows of ST. O'm not sure if we want to do this in the foreseeable future... Maybe some time we'll do it, but not for now.

Thanks for the understanding.
