### ISSUE TITLE
cannot minify any file

### ISSUE THREAD

**Issue by unalignedcoder** [tssajo/Minify#48]
I get this error: "<path+filename> was unexpected at this time"

I get the same error from Sublime text or in the console, CSS HTML or js. 

However, once I put quotes around the file name in the console, it works. Any way to make this directly work from Sublime Text?

**Comment by unalignedcoder** [comment]
There seem to be an issue with the path my files are in, possibly the presence of brackets ( ) in the path.

**Comment by tssajo** [comment]
@unalignedcoder If you give me your full path to your file then I'll try to recreate to issue on my machine.
I can only fix it if I am able to reproduce it.

**Comment by unalignedcoder** [comment]
Just but brackets ( ) in your path and it will be reproduced.

**Comment by tssajo** [comment]
@unalignedcoder What platform are you on? Windows?

**Comment by unalignedcoder** [comment]
I've just said it... :)) I'm on windows

**Comment by tssajo** [comment]
@unalignedcoder The issue has been fixed in version 1.2.7 of `Minify`. Please re-open this issue if you still experience the problem after upgrading to version 1.2.7. Thanks!
