### ISSUE TITLE
CSS Media Queries

### ISSUE THREAD

**Issue by n3ssi3** [tssajo/Minify#52]
Are media queries supported?
I installed it on Sublime Text 3, Mac, and my css breaks with the media queries

**Comment by tssajo** [comment]
@n3ssi3 Thanks for reporting the issue. Unfortunately, there are problems with the 3rd party `clean-css-cli` program lately. I suggest you to try to downgrade it to a v3.x.x release. I can give you instructions:

Open up a Terminal then:

`npm uninstall -g clean-css-cli`
`npm install clean-css@3.4.24`

I hope this resolves your issue.
