### ISSUE TITLE
Save .min in another file

### ISSUE THREAD

**Issue by alanTorresManci** [tssajo/Minify#54]
I´m trying to save the minified file in another path, and avoid the .min extension, is that possible?

**Comment by tssajo** [comment]
@alanTorresManci Sorry for the late reply... Unfortunately, what you want is not supported at the moment and quiet honestly I do not plan to implement it. I do not have the time and I don't really need this feature. Sorry.

**Comment by pavelkunes** [comment]
@tssajo Hello, is there some way, how to easily edit Minify.py file in my Mac to save minified files to parent folder? I found outfile variable in that file but I don't know Python, so I don't know how to add parent path. Can you help me please? Thank you
