### ISSUE TITLE
nth-of-type and nth-child minified with n removed

### ISSUE THREAD

**Issue by mabuki** [tssajo/Minify#55]
Not sure what's changed because this was working, but now if I minify css with nth-of-type(3n+2) I get nth-of-type(3+2) i.e. 'n' is removed, so resulting css doesn't work.

**Comment by tssajo** [comment]
@mabuki Do you use [clean-css](https://github.com/jakubpawlowicz/clean-css) or [uglifycss](https://github.com/fmarcia/UglifyCSS) ? The `Minify` plugin for Sublime Text supports both.
(FYI, [clean-css](https://github.com/jakubpawlowicz/clean-css) is the default.)

This bug needs to be filed to one of these projects. The `Minify` plugin for Sublime Text does not do the actual minification. `Minify` relies on external dependencies, those external programs do the actual minification. `Minify` is just the glue between Sublime Text and those dependencies.

**Comment by mabuki** [comment]
Using default clean-css.

An update to node and npm has resolved the issue.

Thanks
