### ISSUE TITLE
CSS source maps contain absolute paths with extra slashes in sources object

### ISSUE THREAD

**Issue by klined** [tssajo/Minify#56]
Hello. I love this plugin. You've done awesome work!

I am having a small problem though. When I minify my CSS files, my source map's sources object looks like this:
{"version":3,"sources":["L:\\\path\\\to\\\file\\\file.css"],"names":[],"mappings":"..."}

I need the sources object to not contain the path.  Am I missing an option to prevent this from happening somewhere?

**Comment by dkline03** [comment]
Although this probably is not the most elegant solution, I updated the python script with:

`class MinifyClass(MinifyUtils):
	def minify(self):
		inpfile = self.view.file_name()
		**cwd = False**
		if type(inpfile).__name__ in ('str', 'unicode') and re.search(r'\.[^\.]+$', inpfile):
			if self.view.is_dirty() and self.get_setting('save_first'):
				self.view.run_command('save')
				if self.get_setting('auto_minify_on_save'):
					return
			outfile = re.sub(r'(\.[^\.]+)$', r'.min\1', inpfile, 1)
			syntax = self.view.settings().get('syntax')
			if self.get_setting('debug_mode'):
				print('Minify: Syntax: ' + str(syntax))
			if re.search(r'\.js$', inpfile) or re.search(r'/JavaScript\.tmLanguage$', syntax):
				cmd = self.fixStr(self.get_setting('uglifyjs_command') or 'uglifyjs').split()
				cmd.extend([self.quoteChrs(inpfile), '-o', self.quoteChrs(outfile), '-m', '-c'])
				eo = self.get_setting('uglifyjs_options')
				if type(eo).__name__ in ('str', 'unicode'):
					cmd.extend(self.fixStr(eo).split())
				if self.get_setting('source_map'):
					head, tail = ntpath.split(outfile)
					mapfile = tail or ntpath.basename(head)
					cmd.extend(['--source-map', self.quoteChrs(outfile) + '.map', '--source-map-url', self.quoteChrs(mapfile) + '.map', '--source-map-root', './', '-p', 'relative'])
				if self.get_setting('keep_comments'):
					cmd.extend(['--comments'])
					eo = self.get_setting('comments_to_keep')
					if type(eo).__name__ in ('str', 'unicode'):
						cmd.extend([eo])
			elif re.search(r'\.json$', inpfile) or re.search(r'/JSON\.tmLanguage$', syntax):
				cmd = self.fixStr(self.get_setting('minjson_command') or 'minjson').split()
				cmd.extend([self.quoteChrs(inpfile), '-o', self.quoteChrs(outfile)])
			elif re.search(r'\.css$', inpfile) or re.search(r'/CSS\.tmLanguage$', syntax):
				minifier = self.get_setting('cssminifier') or 'clean-css'
				if minifier == 'uglifycss':
					cmd = self.fixStr(self.get_setting('uglifycss_command') or 'uglifycss').split()
					eo = self.get_setting('uglifycss_options')
					if type(eo).__name__ in ('str', 'unicode'):
						cmd.extend(self.fixStr(eo).split())
					cmd.extend([self.quoteChrs(inpfile), '>', self.quoteChrs(outfile)])
				elif minifier == 'yui':
					cmd = self.fixStr(self.get_setting('java_command') or 'java').split()
					yui_compressor = self.get_setting('yui_compressor') or 'yuicompressor-2.4.7.jar'
					cmd.extend(['-jar', PLUGIN_DIR + '/bin/' + str(yui_compressor), self.quoteChrs(inpfile), '-o', self.quoteChrs(outfile)])
					eo = self.get_setting('yui_charset')
					if type(eo).__name__ in ('str', 'unicode'):
						cmd.extend(['--charset', eo])
					eo = self.get_setting('yui_line_break')
					if type(eo).__name__ in ('int', 'str', 'unicode'):
						cmd.extend(['--line-break', str(eo)])
				else:
					**cwd = os.getcwd();
					inpdir = re.sub(r'(\\[^\\]+)$', r'', inpfile, 1)
					os.chdir(inpdir+'\\')**
					cmd = self.fixStr(self.get_setting('cleancss_command') or 'cleancss').split()
					eo = self.get_setting('cleancss_options') or '--s0 -s --skip-rebase'
					if type(eo).__name__ in ('str', 'unicode'):
						cmd.extend(self.fixStr(eo).split())
					if self.get_setting('css_source_map'):
						cmd.extend(['--source-map'])
					cmd.extend(['-o', self.quoteChrs(outfile), self.quoteChrs(inpfile)])
			elif re.search(r'\.html?$', inpfile) or re.search(r'/HTML\.tmLanguage$', syntax):
				cmd = self.fixStr(self.get_setting('html-minifier_command') or 'html-minifier').split()
				eo = self.get_setting('html-minifier_options') or '--collapse-boolean-attributes --collapse-whitespace --html5 --minify-css --minify-js --preserve-line-breaks --process-conditional-comments --remove-comments --remove-empty-attributes --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes'
				if type(eo).__name__ in ('str', 'unicode'):
					cmd.extend(self.fixStr(eo).split())
				cmd.extend(['-o', self.quoteChrs(outfile), self.quoteChrs(inpfile)])
			elif re.search(r'\.svg$', inpfile):
				cmd = self.fixStr(self.get_setting('svgo_command') or 'svgo').split()
				eo = self.get_setting('svgo_min_options')
				if type(eo).__name__ in ('str', 'unicode'):
					cmd.extend(self.fixStr(eo).split())
				cmd.extend([self.quoteChrs(inpfile), self.quoteChrs(outfile)])
			else:
				cmd = False
			if cmd:
				print('Minify: Minifying file:' + str(inpfile))
				print('Minify cmd: '+str(cmd))
				self.run_cmd(cmd, outfile)
				if cwd:
					os.chdir(cwd)`

I'm still hoping that there's some option that I missed.
