### ISSUE TITLE
"toplevel": true not working in Minify.sublime-settings

### ISSUE THREAD

**Issue by perusering** [tssajo/Minify#57]
Via the command line, this successfully changes top level function names...

uglifyjs --compress --mangle toplevel test.js

But if I specify ""toplevel": true" in Minify.sublime-settings nothing changes.  How am I supposed to signal to sublime text to rename top level functions?  Thanks.

**Comment by tssajo** [comment]
@perusering 

`"uglifyjs_options": "--compress --mangle toplevel"`

**Comment by danielprosser1** [comment]
Thanks for the quick response.  When I alter Minify.sublime-settings to include that line and minify test.js I see this error...

uglifyjs /Applications/MAMP/myWebsiteHome/js/test.js -o  /Applications/MAMP/myWebsiteHome/js/testJs.min.js -m -c --compress --mangle toplevel

Error parsing arguments for flag `c': (), ()

**Comment by perusering** [comment]
Thanks for the quick response. When I alter Minify.sublime-settings to include that line and minify test.js I see this error...

uglifyjs /Applications/MAMP/myWebsiteHome/js/test.js -o /Applications/MAMP/myWebsiteHome/js/testJs.min.js -m -c --compress --mangle toplevel

Error parsing arguments for flag `c': (), ()

**Comment by tssajo** [comment]
Please consult the documentation of uglifyjs here:
https://github.com/mishoo/UglifyJS2

**Comment by perusering** [comment]
But this isn't an uglify problem because it's working perfectly when I run it via the command line.

Actually, I just figured it out after re-reading the message I included; the actual line in Minify.sublime-settings should just be...

"uglifyjs_options": "toplevel",

Because it seems like Minify automatically adds -m and -c to the command line output so you don't need --compress and --mangle

Thanks again for the help and super-fast responses
