### ISSUE TITLE
Output "dist" for .js minification

### ISSUE THREAD

**Issue by ushergrey** [tssajo/Minify#58]
Hello,

Is there any options for output **dist** for .js minification

Thanx.

**Comment by tssajo** [comment]
@ushergrey I'm sorry, I do not know what do you mean by "output dist" ... What is that?

**Comment by ushergrey** [comment]
Hi,

I mean the output destination. I want to save the **js minified** files to another folder.

Is there any options for that?


Thanx

**Comment by tssajo** [comment]
Sorry, but this is not supported by the plugin at the moment. It is not trivial to implement and I do not have the time to do it. My goal is to keep this plugin very simple, placing the minified file next to the original file (in the same directory) achieves this goal.
