### ISSUE TITLE
The Context Menu inside the Sublime Text editor window is inactive (grey).

### ISSUE THREAD

**Issue by Janos1973** [tssajo/Minify#60]
Hello, I need some help please.

Installed Minify, Node.js, and the required Node.js CLI apps.
The Context Menu inside the Sublime Text editor window is inactive (grey) and does not do anything.

Can you help me please, how can i fix this issue?

I use Sublime text 3126 stabil on Mac OS Sierra

**Comment by tssajo** [comment]
@Janos1973 
You need to open a file with a file type which can be minified (e.g. a .css file or a .js file). Then it won't be grayed out. This plugin works with files only. You cannot minify an unsaved buffer.

**Comment by Janos1973** [comment]
Oh, sorry. I tried with HTML content but a .php file. :-) thank you for your kind help.
