### ISSUE TITLE
Doesn't work in Sublime Text 3 on Mac

### ISSUE THREAD

**Issue by geoidesic** [tssajo/Minify#63]
Hi,

This plugin doesn't work for me anymore since I upgraded to Sublime Text 3. I tried uninstalling and re-installing. No go. When I try it it produces this error:

`env: node: No such file or directory`

The odd thing is that if I copy the output of the error and run it on the command line manually, it works just fine – produces the correct minified file. So I don't understand why it's not working from Sublime. I'm on Mac OS X Sierra. Node is installed globally, as is uglify.

The command output in the error popup (which works if I use it manually on the command line) is:

`/usr/local/bin/uglify /path/to/the/source/file/to/minify/myfile.js  -o /path/to/destination/file/myfile.min.js -m -c`

**Comment by tssajo** [comment]
@geoidesic Thanks for reporting this. I need a bit more info from you. Please open a Terminal and issue the following command and send me the output:
`which node`
Basically, I'd like to know what is the path to your node binary. FYI: It should be in `/usr/local/bin` directory. If it's not there that could cause this.

**Comment by geoidesic** [comment]
@tssajo It's not there:

`/Users/noeldacosta/.nvm/versions/node/v8.4.0/bin/node`

**Comment by geoidesic** [comment]
I recall around the same time I upgraded Sublime I also switched to using nvm for node management because some apps needed an old version of node and some needed newer versions.

**Comment by tssajo** [comment]
@geoidesic Try to fix it by creating a symlink. Open a Terminal and issue this command:
`cd /usr/local/bin && ln -s /Users/username/.nvm/versions/node/v8.4.0/bin/node node`
I hope this helps. Please let me know.

**Comment by geoidesic** [comment]
@tssajo Yes, that worked. Thanks!
