### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by geoidesic** [tssajo/Minify#65]
Hi,

This plugin used to work wonders. Now it has stopped working and I don't know why. I get the following error:

```
uglifyjs /Users/geoidesic/graph.js -o /Users/geoidesic/graph.min.js -m -c

env: node: No such file or directory
```

However the same command line works if I copy and paste it into the terminal.

**Comment by tssajo** [comment]
@geoidesic I assume you are on macOS, correct?

This sort of issue happens when nodejs is not installed to the usual directory.

You already had this same problem once before and at that time we solved it by creating a symlink. See: https://github.com/tssajo/Minify/issues/63

**Comment by geoidesic** [comment]
You are a legend!
