### ISSUE TITLE
ctrl + s  or "auto_minify_on_save" : true not working

### ISSUE THREAD

**Issue by tarakeshp** [tssajo/Minify#66]
I have a file say sample.js with  2 lines of javascript code.
1. When i do ctrl + s, it didnt create a min file
2. as per the doc ctrl + alt + m created a min file, however when on saving the new lines of code the min file is not getting updated.

Am I missing something ? Any help would be appreciated.

This is my user.settings file

{
    "settings": {
        "Minify": {
            "open_file": false,
            "auto_minify_on_save": true,
            "allowed_file_types": [
                "css",
                "js",
                "svg"
            ]
        }
    }
}

**Comment by tssajo** [comment]
@tarakeshp Hey, sorry about responding so late!

For `auto_minify_on_save` to work, you should have a `Packages/User/Minify.sublime-settings` file that looks something like this:
```
{
	// Save file before doing any action (minify or beautify)?
	"save_first": true,

	// Auto-minify files on save?
	"auto_minify_on_save": true,

	// Open resulting file (minified or beautified)?
	"open_file": false,

	// Only Minify specified file types (css, js, json, html, svg) when "auto_minify_on_save" is used
	"allowed_file_types": [
		"css",
		"js",
		"svg"
	]
}
```
The above are my global settings. Perhaps you were confusing global settings with per project settings on your setup?

The `auto_minify_on_save` features works for me just fine for years. Even after the latest update to SublimeText Version 3.2 Build 3200. So I am closing this Issue now.
