### ISSUE TITLE
Minify fails to recognize 'const'

### ISSUE THREAD

**Issue by AquaJew** [tssajo/Minify#70]
Tried to run minify in sublime on my JavaScript, and got a big nasty popup with uglifyjs:

Parse error at [FILENAME] 
"const IMAGES = document.querySelectorAll("img");

ERROR: Unexpected token: keyword (const)

Does minify fail to support ES6?

**Comment by tssajo** [comment]
The Minify plugin is just the bond between SublimeText editor and [UglifyJS](https://github.com/mishoo/UglifyJS2). The actual minification is done by UglifyJS which is a program written in Javascript. That program is not written nor maintained by me.
