### ISSUE TITLE
uglifyjs is deprecated

### ISSUE THREAD

**Issue by geoidesic** [tssajo/Minify#73]
The README still refers to it.
I see some closed issues regarding uglify-js, which makes me think that Minify already supports uglify-js but there's nothing in the README about that.

**Comment by tssajo** [comment]
@geoidesic UglifyJS is not part of this project, it is just an external dependency. If you already have UglyfyJS installed on your system then it is your responsibility to periodically update UglifyJS. It is in the README file:

If you already have some or all of the above Node.js CLI apps installed on your system then it is recommended to update them all to the latest version with the following command:

`npm update -g clean-css-cli uglifycss js-beautify html-minifier uglify-js minjson svgo`
