### ISSUE TITLE
Installing minify in Ubuntu 16.04

### ISSUE THREAD

**Issue by msj2** [tssajo/Minify#74]
Hi, I use Sublime Build 3126

Ubuntu 16.04
I do have 
Node v9.11.2 installed

I got error installing Minify.

> DPI scale: 1
> startup, version: 3126 linux x64 channel: stable
> executable: /opt/sublime_text/sublime_text
> working dir: /
> packages path: /home/ekagga/.config/sublime-text-3/Packages
> state path: /home/ekagga/.config/sublime-text-3/Local
> zip path: /opt/sublime_text/Packages
> zip path: /home/ekagga/.config/sublime-text-3/Installed Packages
> ignored_packages: ["Vintage"]
> pre session restore time: 0.116707
> startup time: 0.192542
> first paint time: 0.197716
> first paint time: 0.215256
> reloading plugin Default.auto_indent_tag
> reloading plugin Default.block
> reloading plugin Default.comment
> reloading plugin Default.convert_syntax
> reloading plugin Default.copy_path
> reloading plugin Default.delete_word
> reloading plugin Default.detect_indentation
> reloading plugin Default.duplicate_line
> reloading plugin Default.echo
> reloading plugin Default.exec
> reloading plugin Default.fold
> reloading plugin Default.font
> reloading plugin Default.goto_line
> reloading plugin Default.history_list
> reloading plugin Default.indentation
> reloading plugin Default.install_package_control
> reloading plugin Default.kill_ring
> reloading plugin Default.mark
> reloading plugin Default.new_templates
> reloading plugin Default.open_context_url
> reloading plugin Default.open_in_browser
> reloading plugin Default.pane
> reloading plugin Default.paragraph
> reloading plugin Default.paste_from_history
> reloading plugin Default.profile
> reloading plugin Default.quick_panel
> reloading plugin Default.run_syntax_tests
> reloading plugin Default.save_on_focus_lost
> reloading plugin Default.scroll
> reloading plugin Default.set_unsaved_view_name
> reloading plugin Default.settings
> reloading plugin Default.show_scope_name
> reloading plugin Default.side_bar
> reloading plugin Default.sort
> reloading plugin Default.swap_line
> reloading plugin Default.switch_file
> reloading plugin Default.symbol
> reloading plugin Default.transform
> reloading plugin Default.transpose
> reloading plugin Default.trim_trailing_white_space
> reloading plugin CSS.css_completions
> reloading plugin Diff.diff
> reloading plugin HTML.encode_html_entities
> reloading plugin HTML.html_completions
> reloading plugin 0_package_control_loader.00-package_control
> reloading plugin Package Control.1_reloader
> reloading plugin Package Control.2_bootstrap
> Unable to find cancel_build command: exec
> Unable to find cancel_build command: exec
> reloading plugin Package Control.Package Control
> plugins loaded
> Package Control: No updated packages
> ignored packages updated to: ["Minify", "Vintage"]
> reloading settings Packages/User/Package Control.sublime-settings
> reloading settings Packages/User/Preferences.sublime-settings
> Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))) downloading https://codeload.github.com/tssajo/Minify/zip/1.2.7.
> error: Package Control
> 
> Unable to download Minify. Please view the console for more details.
> ignored packages updated to: ["Vintage"]

**Comment by tssajo** [comment]
@msj2 It seems to me that there is an SSL/TLS certificate issue on the codeload.github.com site, see this error:
`Host codeload.github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))`
However, I can download that zip file with no problem using the latest Chrome web browser on Windows.
So I believe that there is an issue with your Ubuntu OS : it appeares that it cannot verify certain SSL/TLS certificates.
I suggest that you update all SSL/TLS related packages on your Ubuntu system using `apt`.

Anyway, it is definitely not an issue with the Minify program so I am closing this Issue.

**Comment by tssajo** [comment]
@msj2 I also suggest that you google this phrase:

`Package Control: Error downloading package. HTTP exception InvalidCertificateException Host returned an invalid certificate`

One of the suggested fixes should resolve your issue with Package Control, too.
