### ISSUE TITLE
auto minfy do not work

### ISSUE THREAD

**Issue by strukturart** [tssajo/Minify#75]
Hello,

auto-minfy js,css files do not work
this are my settings

{
"settings": {
"Minify": {
"open_file": true,
"auto_minify_on_save": true,
"allowed_file_types": [
"css",
"js"
]
}
}
}

manually stg+alt+m works

sublime 3

**Comment by tssajo** [comment]
@strukturart Man, we need more details than that!! :)

**Comment by strukturart** [comment]
Hello,

auto-minfy js,css files do not work
this are my settings

{
    "settings": {
        "Minify": {
            "open_file": true,
            "auto_minify_on_save": true,
            "allowed_file_types": [
                "css",
                "js"
            ]
        }
    }
}

manually stg+alt+m works

**Comment by tssajo** [comment]
This is "per project settings"

I suggest that you try to use the User customized global settings instead. That would apply to all projects, globally.

Go to `Preferences` -> `Package Settings` -> `Minify` and first open `Settings -- Default` but do NOT make any changes there!!! Just highlight the whole thing ( `Ctrl+A` ) and copy it to the clipboard ( `Ctrl+C` ) then you can close this file.
Now go to `Preferences` -> `Package Settings` -> `Minify` and now open the `Settings -- User` file and once again highlight the whole thing ( `Ctrl+A` ) and then delete it ( `Del` ). Then use the Paste function ( `Ctrl + V` ) to copy here the stuff from the clipboard and then save it ( `Ctrl + S` ). Now you have User settings that are identical to the Default settings. You can start customizing your User settings here, in this file.

I hope the above helps!

**Comment by strukturart** [comment]
Yes thank you now it works.
