### ISSUE TITLE
Feature request: minify multiple files

### ISSUE THREAD

**Issue by azrin1972** [tssajo/Minify#8]
Hi - thanks for this great package. I'm requesting for minify/beautify multiple files feature since Im working on multiple js files. maybe selecting the main folder and minify the files under that folder of we can add the files that we are working to a list to be minified/beautified.

Also another possibility is to have a file to be minified on save.

**Comment by tssajo** [comment]
@azrin1972 In `Minify` v1.1.2 there is a new option (see `Minify.sublime-settings` file) called `auto_minify_on_save`. When you set it to `true` the plugin will auto-minify files on save.
Note: It is advised to set `open_file` to `false` when you set `auto_minify_on_save` to `true`.

**Comment by hatted** [comment]
Thanks.  Great plugin.  So what you mean is we just need to open all required .html, .css, .js in Sublime.  Then go to File -> Save All ?

**Comment by tssajo** [comment]
@hatted Yes, that should work fine. But I never tried the Save All function. I usually just Save a single file at a time. Of course, first you have to install the plugin properly and then set `auto_minify_on_save` to `true` in its config file. If you try it, please let me know if it worked or not. Thanks!
