### ISSUE TITLE
Does nothing

### ISSUE THREAD

**Issue by BarbzYHOOL** [tssajo/Minify#81]
It does nothing for me, even after sublime reboot.

**Comment by tssajo** [comment]
Well, it works for thousands of people including myself so there must be something that you do wrong.

**Comment by BarbzYHOOL** [comment]
I install everything with npm, I press minify and nothing

I probably made a mistake, maybe I should have made a prayer before

**Comment by tssajo** [comment]
@BarbzYHOOL I'd help you if I could but you gave zero info... What platform? Windows? MacOS? Linux?
Are you trying to minify a css file? Or a javascript file? Or what?
Does minifying a file from the command line work?
If you only tell "it does nothing" then nobody can help you...

**Comment by BarbzYHOOL** [comment]
I don't know what to report, I read the readme and it's not working so I have no idea what to do.

I'm on linux, I tried to minify or beautify a remote and a local file (minified javascript). But I also tried a css file.

I don't know how to do it from the command line either

**Comment by BarbzYHOOL** [comment]
Ok Just tried this

```
cleancss default.css                                                                                                              

#main #loading{display:none;height:23px;width:23px}#general_info{display:flex;padding:10px;margin:5px}#general_info .general_info{flex:1}#slider_wrapper{width:708px;height:205px;margin-bottom:10px}#slider{overflow:hidden}.item_feral_power{color:#ff7c0a}.item_description{color:#ffd200}.clear{clear:both;height:0;overflow:hidden}:focus{outline:0}.avatar{float:left;margin-right:10px;margin-left:10px;margin-top:3px}.fluxslider,.image1,.image2,.images,.surface{-webkit-transform:translate3D(0,0,0);transform:translate3D(0,0,0)}input[type=radio]{background-color:transparent!important}.pagination{display:none}.caption{padding
```

Apparently that does nothing.

But with the plugin in sublimetext it does nothing too and it doesn't save a copy (probably normal since nothing is modified)

**Comment by BarbzYHOOL** [comment]
uglifycss seems to work in command line, goddamnit -__-

**Comment by tssajo** [comment]
For cleancss CLI instructions please visit
https://github.com/jakubpawlowicz/clean-css-cli#use

Try:
`cleancss -o default.min.css default.css`

**Comment by BarbzYHOOL** [comment]
Ok cleancss works in CLI.

Now if I try to press the "minify" button in sublimetext, it does nothing

**Comment by tssajo** [comment]
@BarbzYHOOL I assume that you opened a local CSS file first in SublimeText editor, correct?

**Comment by BarbzYHOOL** [comment]
I took the same CSS file, I opened it with sublimetext in one of my workspace and I clicked minify
